default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root # ユーザー名を設定
  password: natsumi6136 # パスワードを設定
  host: localhost # ホストを設定
  database: mydatabase # データベース名を設定

development:
  <<: *default

test:
  <<: *default
  database: mydatabase_test # テスト用のデータベース名を設定

production:
  <<: *default
  database: mydatabase_production # 本番用のデータベース名を設定
